# TW cities

[
    {
        :name => 'Siji',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.48694,
        :lon => 121.426109,
    },
    {
        :name => 'Daxi',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.88373,
        :lon => 121.290428,
    },
    {
        :name => 'Puli',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.966391,
        :lon => 120.969521,
    },
    {
        :name => 'Lugu',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.746389,
        :lon => 120.752502,
    },
    {
        :name => 'Wuyi',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.041941,
        :lon => 120.73278,
    },
    {
        :name => 'Jiali',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.021469,
        :lon => 121.606262,
    },
    {
        :name => 'Yilan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.5425,
        :lon => 121.633614,
    },
    {
        :name => 'Yilan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.757,
        :lon => 121.752998,
    },
    {
        :name => 'Yuren',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.0275,
        :lon => 121.542778,
    },
    {
        :name => 'Taibao',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.45944,
        :lon => 120.332222,
    },
    {
        :name => 'Nangan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 26.150391,
        :lon => 119.932838,
    },
    {
        :name => 'Lugang',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.05583,
        :lon => 120.434998,
    },
    {
        :name => 'Taipei',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.94702,
        :lon => 121.581749,
    },
    {
        :name => 'Taipei',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 25.04776,
        :lon => 121.531853,
    },
    {
        :name => 'Zhubei',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.838329,
        :lon => 121.007782,
    },
    {
        :name => 'Taipei',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 25.025881,
        :lon => 121.651611,
    },
    {
        :name => 'Tainan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.000019,
        :lon => 120.188759,
    },
    {
        :name => 'Tainan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.990829,
        :lon => 120.213333,
    },
    {
        :name => 'Pojiao',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 25.08622,
        :lon => 121.223083,
    },
    {
        :name => 'Miaoli',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.56427,
        :lon => 120.823669,
    },
    {
        :name => 'Magong',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.565399,
        :lon => 119.586273,
    },
    {
        :name => 'Erqiao',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.549999,
        :lon => 120.366669,
    },
    {
        :name => 'Fukien',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.68446,
        :lon => 121.764221,
    },
    {
        :name => 'Taiwan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24,
        :lon => 121,
    },
    {
        :name => 'Taiwan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.15114,
        :lon => 120.705406,
    },
    {
        :name => 'Yujing',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.124929,
        :lon => 120.46138,
    },
    {
        :name => 'Guting',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 25.033331,
        :lon => 121.51667,
    },
    {
        :name => 'Guomin',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24,
        :lon => 121.616669,
    },
    {
        :name => 'Shalun',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.81361,
        :lon => 120.945,
    },
    {
        :name => 'Yunlin',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.70701,
        :lon => 120.384811,
    },
    {
        :name => 'Douliu',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.70944,
        :lon => 120.543327,
    },
    {
        :name => 'Nantou',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.83419,
        :lon => 120.92704,
    },
    {
        :name => 'Nantou',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.915661,
        :lon => 120.663872,
    },
    {
        :name => 'Songwu',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.94389,
        :lon => 121.206108,
    },
    {
        :name => 'Laodian',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.4575,
        :lon => 120.406113,
    },
    {
        :name => 'Wucheng',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.56588,
        :lon => 119.624107,
    },
    {
        :name => 'Chishan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.639231,
        :lon => 120.356468,
    },
    {
        :name => 'Banqiao',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 25.014271,
        :lon => 121.467194,
    },
    {
        :name => 'Hualien',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.78166,
        :lon => 121.393333,
    },
    {
        :name => 'Gaoqiao',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.56139,
        :lon => 121.178329,
    },
    {
        :name => 'Lindefu',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.62184,
        :lon => 120.319832,
    },
    {
        :name => 'Keelung',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 25.12825,
        :lon => 121.741898,
    },
    {
        :name => 'Keelung',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 25.114861,
        :lon => 121.689873,
    },
    {
        :name => 'Hsinchu',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.80361,
        :lon => 120.968613,
    },
    {
        :name => 'Xinying',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.30694,
        :lon => 120.310562,
    },
    {
        :name => 'Taitung',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.759911,
        :lon => 121.144569,
    },
    {
        :name => 'Taoyuan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.989599,
        :lon => 121.318703,
    },
    {
        :name => 'Guoxizi',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 25.039129,
        :lon => 121.128304,
    },
    {
        :name => 'Jincheng',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.43667,
        :lon => 118.318329,
    },
    {
        :name => 'Xincheng',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.03334,
        :lon => 121.605988,
    },
    {
        :name => 'Chonglan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.692551,
        :lon => 120.485023,
    },
    {
        :name => 'Fengshan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.626591,
        :lon => 120.361259,
    },
    {
        :name => 'Xianeibu',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 25.017719,
        :lon => 121.542473,
    },
    {
        :name => 'Dongshan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.27306,
        :lon => 120.6325,
    },
    {
        :name => 'Taichung',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.1469,
        :lon => 120.683899,
    },
    {
        :name => 'Hengchun',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.004169,
        :lon => 120.743889,
    },
    {
        :name => 'Fengyuan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.25,
        :lon => 120.716942,
    },
    {
        :name => 'Pingtung',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.49555,
        :lon => 120.614441,
    },
    {
        :name => 'Pingtung',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.67135,
        :lon => 120.488136,
    },
    {
        :name => 'Dongbuzi',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 25.00996,
        :lon => 121.306458,
    },
    {
        :name => 'Zhuzilin',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 25.080521,
        :lon => 121.549149,
    },
    {
        :name => 'Huiyaozi',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.76885,
        :lon => 121.12825,
    },
    {
        :name => 'Chang-hua',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.073271,
        :lon => 120.562759,
    },
    {
        :name => 'Jiayi Shi',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.47917,
        :lon => 120.448891,
    },
    {
        :name => 'Zhongliao',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.67417,
        :lon => 121.471939,
    },
    {
        :name => 'Guizikeng',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 25.17627,
        :lon => 121.443199,
    },
    {
        :name => 'Xiguoshan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.425831,
        :lon => 118.349998,
    },
    {
        :name => 'Antoushan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.066059,
        :lon => 120.550819,
    },
    {
        :name => 'Kaohsiung',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.616261,
        :lon => 120.313332,
    },
    {
        :name => 'Kaohsiung',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.634291,
        :lon => 120.366211,
    },
    {
        :name => 'Chikanlou',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23,
        :lon => 120.199997,
    },
    {
        :name => 'Fuxingcun',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 26.16667,
        :lon => 119.949997,
    },
    {
        :name => 'Shibazhang',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.91667,
        :lon => 120.683327,
    },
    {
        :name => 'Longshanli',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.08333,
        :lon => 120.550003,
    },
    {
        :name => 'Zhongdacuo',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.58102,
        :lon => 120.354874,
    },
    {
        :name => 'Shuiyuandi',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.98333,
        :lon => 121.599998,
    },
    {
        :name => 'Touchongbu',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.7775,
        :lon => 121.047218,
    },
    {
        :name => 'Taipei City',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 25.048611,
        :lon => 121.650269,
    },
    {
        :name => 'Zhongkangle',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.7547,
        :lon => 121.098198,
    },
    {
        :name => 'Dingjiaotan',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.26417,
        :lon => 120.729721,
    },
    {
        :name => 'Tongpanqian',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.95417,
        :lon => 120.213608,
    },
    {
        :name => 'Houzhuangzi',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.194019,
        :lon => 120.662033,
    },
    {
        :name => 'Hualien City',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.97694,
        :lon => 121.604439,
    },
    {
        :name => 'Taitung City',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 22.758301,
        :lon => 121.144402,
    },
    {
        :name => 'Taoyuan City',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.993679,
        :lon => 121.296959,
    },
    {
        :name => 'Zhigaozhuang',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.154539,
        :lon => 120.61602,
    },
    {
        :name => 'Penghu County',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.57111,
        :lon => 119.611382,
    },
    {
        :name => 'Hsinchu County',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.67416,
        :lon => 121.16111,
    },
    {
        :name => 'Zhongshanzhuang',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.08016,
        :lon => 120.547096,
    },
    {
        :name => 'Zhongxing New Village',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 23.95908,
        :lon => 120.685158,
    },
    {
        :name => 'T’ai-chung Hsien',
        :state => '',
        :country => 'Taiwan, Province of China',
        :country_code => 'TW',
        :lat => 24.20916,
        :lon => 120.909439,
    },
];
