# VN cities

[
    {
        :name => 'Hue',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 16.466669,
        :lon => 107.599998,
    },
    {
        :name => 'Lagi',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.66667,
        :lon => 107.783333,
    },
    {
        :name => 'Vinh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 18.66667,
        :lon => 105.666672,
    },
    {
        :name => 'Sa Pa',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 22.340231,
        :lon => 103.844147,
    },
    {
        :name => 'Turan',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 16.06778,
        :lon => 108.220833,
    },
    {
        :name => 'Hai Ha',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.616671,
        :lon => 105.23333,
    },
    {
        :name => 'Sa Dec',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.3,
        :lon => 105.76667,
    },
    {
        :name => 'Tan An',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.53333,
        :lon => 106.416672,
    },
    {
        :name => 'Hoi An',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 15.87944,
        :lon => 108.334999,
    },
    {
        :name => 'Son La',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.316669,
        :lon => 103.900002,
    },
    {
        :name => 'Cu Chi',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.96667,
        :lon => 106.466667,
    },
    {
        :name => 'Da Lat',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.94646,
        :lon => 108.441933,
    },
    {
        :name => 'Ca Mau',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 9.17694,
        :lon => 105.150002,
    },
    {
        :name => 'Ha Noi',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.0245,
        :lon => 105.841171,
    },
    {
        :name => 'Tam Ky',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 15.56667,
        :lon => 108.48333,
    },
    {
        :name => 'Phu Ly',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.541109,
        :lon => 105.913887,
    },
    {
        :name => 'My Tho',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.35,
        :lon => 106.349998,
    },
    {
        :name => 'Pleiku',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 13.98333,
        :lon => 108,
    },
    {
        :name => 'Dong Ha',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 16.81625,
        :lon => 107.100311,
    },
    {
        :name => 'Uong Bi',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.033331,
        :lon => 106.783333,
    },
    {
        :name => 'Lao Cai',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 22.48333,
        :lon => 103.949997,
    },
    {
        :name => 'Yen Bai',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.700001,
        :lon => 104.866669,
    },
    {
        :name => 'Bac Kan',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 22.133329,
        :lon => 105.833328,
    },
    {
        :name => 'Can Gio',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.41667,
        :lon => 106.966667,
    },
    {
        :name => 'Tuy Hoa',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 13.08333,
        :lon => 109.300003,
    },
    {
        :name => 'Ben Tre',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.23333,
        :lon => 106.383331,
    },
    {
        :name => 'Ha Dong',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.9725,
        :lon => 105.777222,
    },
    {
        :name => 'Can Tho',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.03333,
        :lon => 105.783333,
    },
    {
        :name => 'Ha Tien',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.38333,
        :lon => 104.48333,
    },
    {
        :name => 'Ha Long',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.951111,
        :lon => 107.080002,
    },
    {
        :name => 'Ha Tinh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 18.33333,
        :lon => 105.900002,
    },
    {
        :name => 'Bim Son',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.07806,
        :lon => 105.860283,
    },
    {
        :name => 'Con Son',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 8.68333,
        :lon => 106.616669,
    },
    {
        :name => 'Son Tay',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.137779,
        :lon => 105.504997,
    },
    {
        :name => 'Kon Tum',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 14.35,
        :lon => 108,
    },
    {
        :name => 'Xóm Pho',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.033331,
        :lon => 105.849998,
    },
    {
        :name => 'Rach Gia',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.01667,
        :lon => 105.083328,
    },
    {
        :name => 'Bien Hoa',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.95,
        :lon => 106.816673,
    },
    {
        :name => 'Chau Doc',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.7,
        :lon => 105.116669,
    },
    {
        :name => 'Cao Bang',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 22.66667,
        :lon => 106.25,
    },
    {
        :name => 'Song Cau',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 13.45,
        :lon => 109.216667,
    },
    {
        :name => 'Dong Hoi',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 17.48333,
        :lon => 106.599998,
    },
    {
        :name => 'Hoa Binh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.81333,
        :lon => 105.338333,
    },
    {
        :name => 'Cao Lanh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.45,
        :lon => 105.633331,
    },
    {
        :name => 'Nam Dinh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.41667,
        :lon => 106.166672,
    },
    {
        :name => 'Bac Ninh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.183331,
        :lon => 106.050003,
    },
    {
        :name => 'Cam Ranh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.92144,
        :lon => 109.159126,
    },
    {
        :name => 'Ha Giang',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 22.83333,
        :lon => 104.98333,
    },
    {
        :name => 'Can Duoc',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.61667,
        :lon => 106.666672,
    },
    {
        :name => 'Vinh Yen',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.309999,
        :lon => 105.596672,
    },
    {
        :name => 'Lang Son',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.83333,
        :lon => 106.73333,
    },
    {
        :name => 'Hung Yen',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.65,
        :lon => 106.066673,
    },
    {
        :name => 'Vung Tau',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.34599,
        :lon => 107.084259,
    },
    {
        :name => 'Tay Ninh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.3,
        :lon => 106.099998,
    },
    {
        :name => 'Tra Vinh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 9.93472,
        :lon => 106.345284,
    },
    {
        :name => 'Viet Tri',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.301941,
        :lon => 105.430832,
    },
    {
        :name => 'Yen Vinh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 18.66667,
        :lon => 105.666672,
    },
    {
        :name => 'Quy Nhon',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 13.76667,
        :lon => 109.23333,
    },
    {
        :name => 'Haiphong',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.85611,
        :lon => 106.68222,
    },
    {
        :name => 'Thanh Hoa',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 19.799999,
        :lon => 105.76667,
    },
    {
        :name => 'Thai Binh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.450001,
        :lon => 106.333328,
    },
    {
        :name => 'Bac Giang',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.26667,
        :lon => 106.199997,
    },
    {
        :name => 'Ninh Binh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.253889,
        :lon => 105.974998,
    },
    {
        :name => 'Dong Xoai',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.53333,
        :lon => 106.916672,
    },
    {
        :name => 'Phong Tho',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 22.533331,
        :lon => 103.349998,
    },
    {
        :name => 'Vinh Long',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.25,
        :lon => 105.966667,
    },
    {
        :name => 'Nha Trang',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 12.25,
        :lon => 109.183327,
    },
    {
        :name => 'Soc Trang',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 9.60333,
        :lon => 105.980003,
    },
    {
        :name => 'Uyen Hung',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.08416,
        :lon => 106.788338,
    },
    {
        :name => 'Hai Duong',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.933331,
        :lon => 106.316673,
    },
    {
        :name => 'Phu Hưu',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.01667,
        :lon => 105.533333,
    },
    {
        :name => 'Ngô Châu',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 13.45,
        :lon => 109.099998,
    },
    {
        :name => 'Quang Ngai',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 15.11667,
        :lon => 108.800003,
    },
    {
        :name => 'Phan Thiet',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.93333,
        :lon => 108.099998,
    },
    {
        :name => 'Phu Khuong',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.28333,
        :lon => 106.133331,
    },
    {
        :name => 'Long Xuyen',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.38333,
        :lon => 105.416672,
    },
    {
        :name => 'Huyen Ba Vi',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.1999,
        :lon => 105.430183,
    },
    {
        :name => 'Thu Dau Mot',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.96667,
        :lon => 106.650002,
    },
    {
        :name => 'Duong GJong',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.21667,
        :lon => 103.966667,
    },
    {
        :name => 'Tuyen Quang',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.82333,
        :lon => 105.218063,
    },
    {
        :name => 'Thai Nguyen',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.592779,
        :lon => 105.84417,
    },
    {
        :name => 'Huyen Yen Lap',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.350019,
        :lon => 105.060143,
    },
    {
        :name => 'Dien Bien Phu',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.383329,
        :lon => 103.01667,
    },
    {
        :name => 'Cam Pha Mines',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.01667,
        :lon => 107.300003,
    },
    {
        :name => 'Ấp Ba',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 16.04056,
        :lon => 108.212502,
    },
    {
        :name => 'Buon Ma Thuot',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 12.66667,
        :lon => 108.050003,
    },
    {
        :name => 'Thi xa Phu Tho',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.39883,
        :lon => 105.22702,
    },
    {
        :name => 'Huyen Thanh Hoa',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.495831,
        :lon => 105.145348,
    },
    {
        :name => 'Huyen Doan Hung',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.6241,
        :lon => 105.185883,
    },
    {
        :name => 'Huyen Tam Thanh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.25564,
        :lon => 105.297752,
    },
    {
        :name => 'Huyen Song Thao',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.420799,
        :lon => 105.139473,
    },
    {
        :name => 'Huyen Thanh Son',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.219879,
        :lon => 105.186142,
    },
    {
        :name => 'Huyen Son Duong',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.70363,
        :lon => 105.404121,
    },
    {
        :name => 'Huyen Phong Chau',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.43498,
        :lon => 105.293137,
    },
    {
        :name => 'Thanh pho Bac Lieu',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 9.285,
        :lon => 105.724442,
    },
    {
        :name => 'Phan Rang-Thap Cham',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.56667,
        :lon => 108.98333,
    },
    {
        :name => 'Lộc Ninh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.85,
        :lon => 106.599998,
    },
    {
        :name => 'Bến Ðình',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.36833,
        :lon => 107.083328,
    },
    {
        :name => 'Thanh pho Ho Chi Minh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.75,
        :lon => 106.666672,
    },
    {
        :name => 'Tỉnh Hà Nam',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.58333,
        :lon => 106,
    },
    {
        :name => 'Tỉnh Cà Mau',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 9.08333,
        :lon => 105.083328,
    },
    {
        :name => 'Tỉnh Gia Lai',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 13.75,
        :lon => 108.25,
    },
    {
        :name => 'Tỉnh Long An',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.66667,
        :lon => 106.166672,
    },
    {
        :name => 'Tỉnh Kon Tum',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 14.75,
        :lon => 107.916672,
    },
    {
        :name => 'Tỉnh Lào Cai',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 22.33333,
        :lon => 104,
    },
    {
        :name => 'Tỉnh Sơn La',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.16667,
        :lon => 104,
    },
    {
        :name => 'Tỉnh Hà Tây',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.83333,
        :lon => 105.666672,
    },
    {
        :name => 'Tỉnh An Giang',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.5,
        :lon => 105.166672,
    },
    {
        :name => 'Hậu Dương',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.133329,
        :lon => 105.76667,
    },
    {
        :name => 'Tỉnh Hà Giang',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 22.75,
        :lon => 105,
    },
    {
        :name => 'Tỉnh Yên Bái',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.5,
        :lon => 104.666672,
    },
    {
        :name => 'Tỉnh Tây Ninh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.33333,
        :lon => 106.166672,
    },
    {
        :name => 'Tỉnh Trà Vinh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 9.83333,
        :lon => 106.25,
    },
    {
        :name => 'Tỉnh Phú Yên',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 13.16667,
        :lon => 109.166672,
    },
    {
        :name => 'Tỉnh Hà Tĩnh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 18.33333,
        :lon => 105.75,
    },
    {
        :name => 'Tỉnh Hòa Bình',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.33333,
        :lon => 105.25,
    },
    {
        :name => 'Tỉnh Vĩnh Long',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.16667,
        :lon => 106,
    },
    {
        :name => 'Tỉnh Ninh Bình',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.25,
        :lon => 105.833328,
    },
    {
        :name => 'Tỉnh Thanh Hóa',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20,
        :lon => 105.5,
    },
    {
        :name => 'Tỉnh Thái Bình',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.5,
        :lon => 106.333328,
    },
    {
        :name => 'Tỉnh Khánh Hòa',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 12.33333,
        :lon => 109,
    },
    {
        :name => 'Tỉnh Hưng Yên',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.83333,
        :lon => 106.083328,
    },
    {
        :name => 'Tỉnh Sóc Trăng',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 9.66667,
        :lon => 105.833328,
    },
    {
        :name => 'Tỉnh Vĩnh Phúc',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.299999,
        :lon => 105.599998,
    },
    {
        :name => 'Tỉnh Tuyên Quang',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 22.116671,
        :lon => 105.25,
    },
    {
        :name => 'Tỉnh Thái Nguyên',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.66667,
        :lon => 105.833328,
    },
    {
        :name => 'Tỉnh Bình Dương',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.16667,
        :lon => 106.666672,
    },
    {
        :name => 'Socialist Republic of Vietnam',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 16.16667,
        :lon => 107.833328,
    },
    {
        :name => 'Tỉnh Bến Tre',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.16667,
        :lon => 106.5,
    },
    {
        :name => 'Tỉnh Bắc Ninh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.08333,
        :lon => 106.166672,
    },
    {
        :name => 'Tỉnh Ðồng Nai',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11,
        :lon => 107.166672,
    },
    {
        :name => 'Tỉnh Bắc Giang',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.33333,
        :lon => 106.333328,
    },
    {
        :name => 'Tỉnh Bạc Liêu',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 9.25,
        :lon => 105.75,
    },
    {
        :name => 'Tỉnh Cần Thơ',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 9.83333,
        :lon => 105.666672,
    },
    {
        :name => 'Tỉnh Lạng Sơn',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.75,
        :lon => 106.5,
    },
    {
        :name => 'Thôn Chiết Bi Ha',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 16.4,
        :lon => 107.716667,
    },
    {
        :name => 'Tỉnh Ðồng Tháp',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.66667,
        :lon => 105.666672,
    },
    {
        :name => 'Tỉnh Hải Dương',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.91667,
        :lon => 106.333328,
    },
    {
        :name => 'Tỉnh Quảng Nam',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 15.58333,
        :lon => 107.916672,
    },
    {
        :name => 'Tỉnh Kiến Giang',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10,
        :lon => 105.166672,
    },
    {
        :name => 'Tỉnh Quảng Ninh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.25,
        :lon => 107.333328,
    },
    {
        :name => 'Tỉnh Tiền Giang',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.41667,
        :lon => 106.166672,
    },
    {
        :name => 'Tỉnh Quảng Bình',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 17.5,
        :lon => 106.333328,
    },
    {
        :name => 'Tỉnh Quảng Ngãi',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 15,
        :lon => 108.666672,
    },
    {
        :name => 'Xóm Yân Lạc Hâu',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 18.73333,
        :lon => 105.666672,
    },
    {
        :name => 'Tỉnh Nghệ An',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 19.33333,
        :lon => 104.833328,
    },
    {
        :name => 'Quảng Trị',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 16.75,
        :lon => 107.199997,
    },
    {
        :name => 'Tỉnh Ðà Nẵng',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 16.08333,
        :lon => 108.083328,
    },
    {
        :name => 'Thông Tây Hội',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.83333,
        :lon => 106.650002,
    },
    {
        :name => 'Tỉnh Cao Bằng',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 22.66667,
        :lon => 106,
    },
    {
        :name => 'Tỉnh Nam Ðịnh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.25,
        :lon => 106.25,
    },
    {
        :name => 'Tỉnh Lâm Ðồng',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.5,
        :lon => 108.333328,
    },
    {
        :name => 'Huyện Ðiện Biên',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.33333,
        :lon => 102.933327,
    },
    {
        :name => 'Tỉnh Phú Thọ',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.33333,
        :lon => 105.166672,
    },
    {
        :name => 'Tỉnh Bà Rịa-Vũng Tàu',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.58333,
        :lon => 107.25,
    },
    {
        :name => 'Tỉnh Bình Ðịnh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 14.16667,
        :lon => 109,
    },
    {
        :name => 'Ấp Vạn Tự Tây',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 12.15,
        :lon => 109.099998,
    },
    {
        :name => 'Thủ Ðô Hà Nội',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 21.116671,
        :lon => 105.883331,
    },
    {
        :name => 'Tỉnh Ninh Thuận',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.75,
        :lon => 108.833328,
    },
    {
        :name => 'Tỉnh Bình Thuận',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.08333,
        :lon => 108,
    },
    {
        :name => 'Tỉnh Bình Phước',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 11.75,
        :lon => 106.916672,
    },
    {
        :name => 'Tỉnh Bắc Kạn',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 22.16667,
        :lon => 105.833328,
    },
    {
        :name => 'Tỉnh Ðắc Lắk',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 12.83333,
        :lon => 108.166672,
    },
    {
        :name => 'Thôn Ðiền Hạ',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 12.25,
        :lon => 109.183327,
    },
    {
        :name => 'Thành Phố Hải Phòng',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 20.83333,
        :lon => 106.583328,
    },
    {
        :name => 'Thành phố Hồ Chí Minh',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 10.83333,
        :lon => 106.666672,
    },
    {
        :name => 'Tỉnh Quảng Trị',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 16.75,
        :lon => 107,
    },
    {
        :name => 'Tỉnh Thừa Thiên-Huế',
        :state => '',
        :country => 'Viet Nam',
        :country_code => 'VN',
        :lat => 16.33333,
        :lon => 107.583328,
    },
];
